name: Add new issues to Walking Skeleton project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project-1:
    name: Add issue to The Overview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/LL782/projects/1/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT_LL782_OVERVIEW }}
  add-to-project-4:
    name: Add issue to Walking Skeleton
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/LL782/projects/4/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT_LL782_OVERVIEW }}
